language: rust

jobs:
  fast_finish: true

cache:
  cargo: true
  directories:
    - ~/.rustup
    - ~/.cargo
    - $TRAVIS_BUILD_DIR/target

matrix:
  include:
    - rust: stable
      script: cargo test
    - rust: stable
      script: cargo test reconnect_test --features=fault_injection -- --ignored
    - rust: 1.37.0
      script: cargo check
  fast_finish: true
