language: rust

jobs:
  fast_finish: true

cache:
  cargo: true
  directories:
    - ~/.rustup
    - ~/.cargo
    - $TRAVIS_BUILD_DIR/target

matrix:
  include:
    - rust: stable
      env: TEST="cargo test --features=fault_injection"
    - rust: 1.37.0
      env: TEST="cargo check"
  fast_finish: true

script: $TEST
