[package]
name = "nats"
version = "0.5.0"
description = "A Rust NATS client"
authors = ["Derek Collison <derek@nats.io>", "Tyler Neely <tyler@nats.io>", "Stjepan Glavina <stjepan@nats.io>"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/nats"
homepage = "https://github.com/nats-io/nats.rs"
repository = "https://github.com/nats-io/nats.rs"
readme = "CRATE.md"
keywords = ["nats", "client", "messaging", "api"]
categories = ["network-programming", "api-bindings"]

[features]
fault_injection = []

[badges]
travis-ci = { repository = "nats-io/nats.rs", branch = "master" }
maintenance = { status = "actively-developed" }

[profile.dev]
panic = 'abort'

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
regex = "1.3.9"
nuid = "0.2.1"
lazy_static = "1.4.0"
nom = "5.1.2"
crossbeam-channel = "0.4.2"
parking_lot = "0.11.0"
rand = "0.7.3"
async-native-tls = "0.3.3"
native-tls = "0.2.4"
log = "0.4.8"
nkeys = "0.0.9"
base64-url = "1.2.0"
once_cell = "1.4.0"
smol = "0.1.18"
piper = "0.1.3"
futures = "0.3.5"
async-mutex = "1.1.4"
itoa = "0.4.6"
blocking = "0.4.6"
async-channel = "1.1.0"

# Delete this dependency when the following issue gets fixed:
# https://github.com/marshallpierce/rust-base64/issues/135
base64 = "0.12.2"

[dev-dependencies]
criterion = "0.3.2"
quicli = "0.4.0"
structopt = "0.3.15"
env_logger = "0.7.1"

[[bench]]
name = "nats_bench"
harness = false

[[example]]
name = "nats-box"
path = "examples/nats-box/main.rs"

[[example]]
name = "serde-json"
path = "examples/serde-json/main.rs"
